In [1]:
import pandas as pd

### Series

In [2]:
# Create
s = pd.Series([1,2,3,4,5])
print(s, type(s))
print("Value at index 1: ",s[1])

s = pd.Series([23,24,25,26], index=["Aman","Pranjal","Ayush","Kaustuv"])
print(s)
print("Age of aman: ",s["Aman"])
print("Age of ayush: ", s.iloc[2])
print(s.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
Value at index 1:  2
Aman       23
Pranjal    24
Ayush      25
Kaustuv    26
dtype: int64
Age of aman:  23
Age of ayush:  25
Index(['Aman', 'Pranjal', 'Ayush', 'Kaustuv'], dtype='str')

In [3]:
# Operations
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1+s2)

s1[0] = 2  # update element
print(s1)

s = s1.drop(0) # drop element
print(s)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    2
1    2
2    3
3    4
4    5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

### Dataframe
- Note: Everytime dataframe will be created as view. To create copy, use .copy()

In [4]:
# Create DataFrame
info = {
    "Name": ["Aman", "Ayush", "Kaustuv", "Pranjal"],
    "Age": [25, 23, 24, 22],
    "CGPA": [9.8, 8.4, 9.2, 8.8]
}
# Using dictionary
df = pd.DataFrame(info)  
print(df, "\n",type(df), "\n")

# Using 2d array
df = pd.DataFrame([["Aman", 25], ["Ayush", 23], ["Kaustuv", 24], ["Pranjal", 22]], columns=["Name", "Age"])
print(df, "\n")

# Using numpy array
import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns=["A", "B", "C"])
print(df, "\n")

print(df.columns)        # Columns Headers
print(df.index)          # Row Headers

      Name  Age  CGPA
0     Aman   25   9.8
1    Ayush   23   8.4
2  Kaustuv   24   9.2
3  Pranjal   22   8.8
 <class 'pandas.DataFrame'>

      Name  Age
0     Aman   25
1    Ayush   23
2  Kaustuv   24
3  Pranjal   22

   A  B  C
0  1  2  3
1  4  5  6

Index(['A', 'B', 'C'], dtype='str')
RangeIndex(start=0, stop=2, step=1)

In [5]:
# Reading from a file
df = pd.read_csv("employee_data.csv")   # csv
print(df, type(df), "\n")

df = pd.read_json("employee_data.json") # json
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [6]:
# Writing to a file
df.to_csv("new_data.csv")

In [38]:
# Methods
print(df.head(), "\n")     # top 5
print(df.tail(), "\n")     # last 5
print(df.sample(3), "\n")  # random
print(df.info(), "\n")     # information
print(df.shape, "\n")      # shape
print(df.describe(), "\n") # description of numerical columns
print(df.columns, "\n")    # list of columns
print(df.nunique(), "\n")  # no. of unique rows per columns

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

   ID   Name  Age Department  Salary
9  10  Julia   30    Finance   60000
3   4  David   45  Marketing   91000
8   9    Ian   35         IT   75000

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes
None

(10, 5)

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

### Practice on AQI Dataset

In [42]:
# Read csv
df = pd.read_csv("globalAirQuality.csv")
print(df.sample(5))

                        timestamp country           city  latitude  longitude  \
3100   2025-11-13 22:25:17.554219      MX    Mexico City    19.433    -99.133
17532  2025-11-15 06:25:17.554219      FI       Helsinki    60.170     24.938
11815  2025-11-17 01:25:17.554219      ID        Jakarta    -6.209    106.846
12157  2025-11-16 07:25:17.554219      AU         Sydney   -33.869    151.209
15311  2025-11-12 17:25:17.554219      US  San Francisco    37.775   -122.419

         pm25    pm10     no2     so2      o3     co  aqi  temperature  \
3100   61.161  79.377  34.332   5.997  46.197  0.870  122       19.427
17532  59.785  81.660  23.948  10.005  34.741  0.767  119       16.014
11815  62.327  53.387  20.082   1.105  49.114  0.646  124       29.476
12157  33.017  64.600  34.418   2.431  59.695  0.737   86       10.933
15311  38.396  14.941  47.289   6.868  57.512  1.150  118        9.193

       humidity  wind_speed
3100     77.901       4.211
17532    37.726       0.906
11815    68.977       7.856
12157    50.654       4.597
15311    84.890       2.217

In [46]:
# Selecting columns
df[["city", "aqi"]].head()

       city  aqi
0  New York  108
1  New York   90
2  New York   84
3  New York  158
4  New York   97

In [50]:
# Selecting rows
df.loc[2]
df.loc[0:2]  # start idx : end idx(inclusive)

df.iloc[2]
df.iloc[0:2] # start idx : end idx(exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [61]:
# Selecting rows & columns
df.loc[0:2, ["city", "aqi"]]

df.iloc[0:2, [2,3,4,11]]
df.iloc[0:2, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [63]:
# Selecting cell
df.at[1, "city"]

df.iat[1, 2]

'New York'

In [69]:
# Filtering Data
filtered_df = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city","aqi","temperature"]]
filtered_df

           city  aqi  temperature
6      New York  155       36.729
7      New York  115       37.891
14     New York  121       34.481
17     New York  127       36.193
25     New York  113       31.289
...         ...  ...          ...
17947    Zurich  107       32.584
17950    Zurich  140       36.885
17975    Zurich  111       30.761
17976    Zurich  146       30.909
17991    Zurich  104       32.556

[2384 rows x 3 columns]

In [74]:
# Differenc between label(original) & index
print("Label 6 data:\n", filtered_df.loc[6])
print("\nIndex 0 data:\n", filtered_df.iloc[0])

Label 6 data:
 city           New York
aqi                 155
temperature      36.729
Name: 6, dtype: object

Index 0 data:
 city           New York
aqi                 155
temperature      36.729
Name: 6, dtype: object

In [76]:
# Filter using query
df.query("aqi < 100 & temperature < 30")[["city", "aqi", "temperature"]]

           city  aqi  temperature
1      New York   90        5.838
4      New York   97       13.632
5      New York   92       15.159
9      New York   76       11.490
10     New York   96       27.913
...         ...  ...          ...
17986    Zurich   38       14.021
17989    Zurich   93       10.150
17992    Zurich   91       14.728
17998    Zurich   95       24.042
17999    Zurich   88        8.529

[6106 rows x 3 columns]