In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
# Read csv
insurance_data = pd.read_csv('insurance.csv')
insurance_data.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [3]:
# Dividing into Inputs and Output
X = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]
# Map
X["sex"] = X["sex"].map({"male": 0, "female": 1})
X["smoker"] = X["smoker"].map({"no": 0, "yes": 1})
X["region"] = X["region"].map({"northeast": 0, "northwest": 1, "southeast": 2, "southwest": 4})

# Test/Train Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict values
y_pred = model.predict(X_test)

# Score
r2 = r2_score(y_test, y_pred)
print("R-squared value: ", r2)
n = X_test.shape[0]
p = X_test.shape[1]
adj_r2 = 1 - ((1-r2)*(n-1) / (n-p-1))
print("Adjusted R-squared value: ", adj_r2)

R-squared value:  0.7828534293784793
Adjusted R-squared value:  0.7778615541917777

### 1. One-Hot Encoding

In [11]:
# Dividing into Inputs and Output
X = insurance_data.drop(columns=["charges"])
y = insurance_data["charges"]
# One-Hot Encoding
X = pd.get_dummies(X, columns=["sex", "smoker", "region"], drop_first=True, dtype=int)

X.head(3)

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,0,1,0,0,1
1,18,33.77,1,1,0,0,1,0
2,28,33.00,3,1,0,0,1,0

In [12]:
# Test/Train Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict values
y_pred = model.predict(X_test)

# Score
r2 = r2_score(y_test, y_pred)
print("R-squared value: ", r2)
n = X_test.shape[0]
p = X_test.shape[1]
adj_r2 = 1 - ((1-r2)*(n-1) / (n-p-1))
print("Adjusted R-squared value: ", adj_r2)

R-squared value:  0.7835929767120722
Adjusted R-squared value:  0.7769085898923679

### 2. Derived Features

In [ ]:
def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Obesity'

df