In [1]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score

In [4]:
# Read csv
heart_df = pd.read_csv("heart.csv")
heart_df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [7]:
# Input/Output Split
X = heart_df.drop(columns=["target"])
y = heart_df["target"]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
132   42    1   1       120   295  ...      0      0.0      2   0     2
202   58    1   0       150   270  ...      1      0.8      2   0     3
196   46    1   2       150   231  ...      0      3.6      1   0     2
75    55    0   1       135   250  ...      0      1.4      1   0     2
176   60    1   0       117   230  ...      1      1.4      2   2     3

[5 rows x 13 columns]

In [11]:
# Logistic Regression
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

In [12]:
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Precision Score: ", precision_score(y_test, y_pred))

Accuracy Score:  0.8852459016393442
Precision Score:  0.8787878787878788