In [39]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [46]:
# Read csv
admission = pd.read_csv('Admission_Predict.csv')
admission.head()

   Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0           1        337          118  ...  9.65         1              0.92
1           2        324          107  ...  8.87         1              0.76
2           3        316          104  ...  8.00         1              0.72
3           4        322          110  ...  8.67         1              0.80
4           5        314          103  ...  8.21         0              0.65

[5 rows x 9 columns]

In [47]:
admission.shape

(400, 9)

In [48]:
# Check min/max
admission.describe()

       Serial No.   GRE Score  ...    Research  Chance of Admit
count  400.000000  400.000000  ...  400.000000        400.000000
mean   200.500000  316.807500  ...    0.547500          0.724350
std    115.614301   11.473646  ...    0.498362          0.142609
min      1.000000  290.000000  ...    0.000000          0.340000
25%    100.750000  308.000000  ...    0.000000          0.640000
50%    200.500000  317.000000  ...    1.000000          0.730000
75%    300.250000  325.000000  ...    1.000000          0.830000
max    400.000000  340.000000  ...    1.000000          0.970000

[8 rows x 9 columns]

In [49]:
# Check null
admission.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [50]:
# Input/Output
X = admission.drop(columns=["Serial No.", "Chance of Admit"])
y = admission["Chance of Admit"]

KeyError: "['Chance of Admit'] not found in axis"

In [30]:
# Train/Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 24)
print(X_train)
print(y_train)

      Store  Holiday_Flag  Temperature  Fuel_Price         CPI  Unemployment
121       1             0        77.95       3.501  221.747214         7.143
6195     44             0        34.90       2.846  126.983581         7.610
3422     24             0        68.13       3.997  138.281452         8.953
6261     44             0        53.20       3.734  130.967097         5.774
1698     12             0        90.47       3.875  130.756267        11.627
...     ...           ...          ...         ...         ...           ...
3473     25             0        42.72       3.000  205.099281         7.484
343       3             0        61.29       3.459  217.465368         7.551
6336     45             0        30.54       3.109  182.551954         8.724
899       7             0        25.56       2.758  191.031217         9.137
4514     32             0        75.64       3.485  194.379637         8.622

[5148 rows x 6 columns]
121     1624477.58
6195     365098.24
3422    1303726.54
6261     310027.29
1698     943124.74
           ...
3473     718056.73
343      404753.30
6336    1002364.34
899      482528.36
4514    1183740.91
Name: Weekly_Sales, Length: 5148, dtype: float64

In [31]:
# Model Train
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [32]:
# Predict
y_pred = model.predict(X_test)

In [33]:
# Evaluate
r2 = r2_score(y_test, y_pred)
print(r2)

0.11547258948329153