In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [3]:
# Read csv
df = pd.read_csv("shop_smart_ecommerce.csv")
df.head(3)

   Administrative  Administrative_Duration  ...  Weekend  Revenue
0               0                      0.0  ...    False    False
1               0                      0.0  ...    False    False
2               0                      0.0  ...    False    False

[3 rows x 18 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  str
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  str
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), str(2)
memory usage: 1.5 MB

In [5]:
# Encoding
df["Weekend"] = df["Weekend"].map({False: 0, True: 1})
df["Revenue"] = df["Revenue"].map({False: 0, True: 1})

# Ordinal Encoding
le = LabelEncoder()
df["VisitorType"] = le.fit_transform(df["VisitorType"])

# Nominal Encoding
df = pd.get_dummies(df, columns=["Month"], drop_first=True, dtype=int)
df.head(3)

   Administrative  Administrative_Duration  ...  Month_Oct  Month_Sep
0               0                      0.0  ...          0          0
1               0                      0.0  ...          0          0
2               0                      0.0  ...          0          0

[3 rows x 26 columns]

In [6]:
# Train-Test Split
X = df.drop(columns=["Revenue"])
y = df["Revenue"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
# Model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Evaluate
print("----- Train Score -----")
print("Accuracy: ", accuracy_score(y_train, y_pred_train))
print("Precision:", precision_score(y_train, y_pred_train))
print("Recall: ", recall_score(y_train, y_pred_train))
print("F1 score: ", f1_score(y_train, y_pred_train))
print("----- Test Score -----")
print("Accuracy: ", accuracy_score(y_test, y_pred_test))
print("Precision:", precision_score(y_test, y_pred_test))
print("Recall: ", recall_score(y_test, y_pred_test))
print("F1 score: ", f1_score(y_test, y_pred_test))

----- Train Score -----
Accuracy:  1.0
Precision: 1.0
Recall:  1.0
F1 score:  1.0
----- Test Score -----
Accuracy:  0.8572587185725872
Precision: 0.5721271393643031
Recall:  0.5693430656934306
F1 score:  0.5707317073170731

In [16]:
# Hyperparameter Tunning
from sklearn.model_selection import GridSearchCV
param = {
    "max_depth": [2, 3, 4, 5, 6]
}
grid = GridSearchCV(
    model,
    param,
    scoring="f1",
    cv=5
)

grid.fit(X_train, y_train)
y_pred_train = grid.predict(X_train)
y_pred_test = grid.predict(X_test)

# Evaluate
print("Best params:", grid.best_params_)
print("----- Train Score -----")
print("Accuracy: ", accuracy_score(y_train, y_pred_train))
print("Precision:", precision_score(y_train, y_pred_train))
print("Recall: ", recall_score(y_train, y_pred_train))
print("F1 score: ", f1_score(y_train, y_pred_train))
print("----- Test Score -----")
print("Accuracy: ", accuracy_score(y_test, y_pred_test))
print("Precision:", precision_score(y_test, y_pred_test))
print("Recall: ", recall_score(y_test, y_pred_test))
print("F1 score: ", f1_score(y_test, y_pred_test))

Best params: {'max_depth': 3}
----- Train Score -----
Accuracy:  0.9015612327656123
Precision: 0.697151424287856
Recall:  0.6212424849699398
F1 score:  0.6570116566584245
----- Test Score -----
Accuracy:  0.8884833738848338
Precision: 0.6976744186046512
Recall:  0.583941605839416
F1 score:  0.6357615894039735